/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.Color;
import javax.swing.*;
import java.util.*;


/**
 *
 * @author Melee & Fede
 */
public class forms1 extends javax.swing.JFrame {

    /**
     * Creates new form forms1
     */
    public forms1() {
        initComponents();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UNITO");
        setLocation(new java.awt.Point(300, 200));
        setMaximumSize(new java.awt.Dimension(620, 630));
        setMinimumSize(new java.awt.Dimension(620, 630));
        setPreferredSize(new java.awt.Dimension(620, 630));
        setSize(new java.awt.Dimension(620, 630));
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(204, 153, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1.png"))); // NOI18N
        jButton1.setAlignmentY(0.0F);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setLabel("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 240, 40, 60);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(80, 240, 50, 60);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3.png"))); // NOI18N
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(150, 240, 50, 60);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/start button.png"))); // NOI18N
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(400, 160, 130, 130);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 280, 190, 180);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(38, 76, 38));
        jTextField1.setFont(new java.awt.Font("akaDylan Plain", 0, 24)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(169, 169, 79));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 430, 70, 38);

        jTextField2.setBackground(new java.awt.Color(38, 85, 38));
        jTextField2.setFont(new java.awt.Font("akaDylan Plain", 0, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(169, 169, 79));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("0");
        jTextField2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jTextField2);
        jTextField2.setBounds(80, 430, 70, 38);

        jTextField3.setBackground(new java.awt.Color(38, 94, 38));
        jTextField3.setFont(new java.awt.Font("akaDylan Plain", 0, 24)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(169, 169, 79));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0");
        jTextField3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jTextField3);
        jTextField3.setBounds(150, 430, 70, 38);

        jTextField4.setBackground(new java.awt.Color(38, 92, 38));
        jTextField4.setFont(new java.awt.Font("akaDylan Plain", 0, 24)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(169, 169, 79));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0");
        jTextField4.setBorder(null);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(460, 440, 50, 40);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 290, 60, 60);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(74, 290, 60, 60);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(144, 290, 60, 60);

        jLabel9.setForeground(new java.awt.Color(179, 179, 89));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/800x800.png"))); // NOI18N
        jLabel9.setMaximumSize(new java.awt.Dimension(600, 600));
        jLabel9.setMinimumSize(new java.awt.Dimension(600, 600));
        jLabel9.setPreferredSize(new java.awt.Dimension(600, 600));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 0, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    int j1,j2,j3,k,nj,pr,rd;
    String ld;
    Random rnd=new Random();
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    nj=1;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    nj=2;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    nj=3;
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    
        if(nj==0){
            JOptionPane.showMessageDialog(null, "Elija numero de jugadores!");
        }else {
            while (j1<100 && j2<100 && j3<100){
              for (k=1;k<=nj;k++){
                  switch (k) {
                      case 1:
                          jLabel2.setIcon(new ImageIcon
                             (getClass().getResource("/img/cubilete.png")));
                          jLabel4.setIcon(new ImageIcon
                             (getClass().getResource("")));
                          jLabel5.setIcon(new ImageIcon
                             (getClass().getResource("")));
                          break;
                      case 2:
                          jLabel4.setIcon(new ImageIcon
                             (getClass().getResource("/img/cubilete.png")));
                          jLabel2.setIcon(new ImageIcon
                             (getClass().getResource("")));
                          jLabel5.setIcon(new ImageIcon
                             (getClass().getResource("")));
                          break;
                      default:
                          jLabel5.setIcon(new ImageIcon
                             (getClass().getResource("/img/cubilete.png")));
                          jLabel4.setIcon(new ImageIcon
                             (getClass().getResource("")));
                          jLabel2.setIcon(new ImageIcon
                             (getClass().getResource("")));
                          break;
                  }
                  ld=JOptionPane.showInputDialog("Lanzar dados? s / n ");
                  while (ld.equalsIgnoreCase("s")){
                      rd=rnd.nextInt(6)+1;
                      jLabel3.setIcon(new ImageIcon 
                     (getClass().getResource("/img/dado"+rd+".png")));
                      jLabel3.setIcon(new ImageIcon (getClass().getResource("/img/dado"+rd+".png")));
                      if (rd==1){
                        JOptionPane.showMessageDialog(null, "pierde el turno");
                        pr=0;
                        ld="n";
                        jTextField4.setText(""+pr);
                        }else{
                        pr=pr+rd;
                        jTextField4.setText(""+pr);
                        ld=JOptionPane.showInputDialog("volver a tirar? s/n");
                        }
                  }
              switch (k) {
                        case 1:
                            j1= j1+pr ;
                            pr =0;
                            jTextField4.setText(""+pr);
                            break;
                        case 2:
                            j2= j2+pr ;
                            pr =0;
                            jTextField4.setText(""+pr);
                            break;
                        case 3:
                            j3= j3+pr ;
                            pr =0;
                            jTextField4.setText(""+pr);
                            break;
            
                        }
              jTextField1.setText(""+j1);
              jTextField2.setText(""+j2);
              jTextField3.setText(""+j3);
              }}
            
        if (nj==1){
           JOptionPane.showMessageDialog(null,"Ganador Jugador 1 con"+j1); 
        }else if (nj==2){
            if (j1>j2){
                JOptionPane.showMessageDialog(null,"Ganador Jugador 1 con"+j1);
            }else{
                JOptionPane.showMessageDialog(null,"Ganador Jugador 2 con"+j2);
            }
        }else{
            if(j1>j2 && j2>j3){
             JOptionPane.showMessageDialog(null,"Ganador Jugador 1 con"+j1);
            }else if (j2>j1 && j2>j3){
             JOptionPane.showMessageDialog(null,"Ganador Jugador 2 con"+j2);
            }else{
             JOptionPane.showMessageDialog(null,"Ganador Jugador 3 con"+j3);
             }
        }
        }  
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forms1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forms1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forms1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forms1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forms1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
